# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credentialsmodel',
            table='credentials',
        ),
    ]
