# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('oauth', '0002_auto_20170117_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='CredentialsModel',
        ),
    ]
